$(document).ready(function(){
    $(window).scroll(function(){
 $("nav").toggleClass("scrolled",$(this).scrollTop()>100)
});
 $('.owl-skills').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    autoplay:1000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1140:{
            items:1
        }
    }
});  
});